### ISSUE TITLE
Add error handling when request failed

### ISSUE THREAD

**Issue by keung227** [CheshireCaat/bas-remote-node#16]
undefined:1
<html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at IncomingMessage.<anonymous> (my_program_path\node_modules\bas-remote-node\src\utils.js:29:20)

There are some issues which force close my program when fetching fingerprint using "puppeteer-with-fingerprints"

**Comment by dmitryp-rebel** [comment]
Also catch same issue continuously:
```
Uncaught exception
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\bots\bot-amazon-180-1\node_modules\bas-remote-node\src\services\utils.js:14:20)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
