### ISSUE TITLE
Can't send data because WebSocket is not opened.

### ISSUE THREAD

**Issue by dmitryp-rebel** [CheshireCaat/bas-remote-node#19]
Hello. I experience occasional but quite often error on launch puppeteer-with-fingerprints plugin:

Version:  puppeteer-with-fingerprints@1.4.3

Thread #0 failed: Error: Can't send data because WebSocket is not opened.
    at exports.throwIf (C:\bots\test\node_modules\websocket-as-promised\src\utils.js:4:11)
    at WebSocketAsPromised.send (C:\bots\test\node_modules\websocket-as-promised\src\index.js:252:5)
    at SocketService.send (C:\bots\test\node_modules\bas-remote-node\src\services\socket.js:89:14)
    at BasRemoteClient._send (C:\bots\test\node_modules\bas-remote-node\src\index.js:223:25)
    at BasRemoteClient.send (C:\bots\test\node_modules\bas-remote-node\src\index.js:254:17)
    at BasRemoteClient._startThread (C:\bots\test\node_modules\bas-remote-node\src\index.js:275:10)
    at C:\bots\test\node_modules\bas-remote-node\src\index.js:190:12
    at new Promise (<anonymous>)
    at BasRemoteClient.runFunction (C:\bots\test\node_modules\bas-remote-node\src\index.js:189:21)
    at C:\bots\test\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:31:16

What could it be a reason?

**Comment by dmitryp-rebel** [comment]
Still getting a lot of those running multiple processes
